//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("EnduranceGoals.Model", "FK_Cities_CountryId", "Countries", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EnduranceGoals.Models.Countries), "Cities", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnduranceGoals.Models.Cities))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("EnduranceGoals.Model", "FK_Venues_CityId", "Cities", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EnduranceGoals.Models.Cities), "Venues", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnduranceGoals.Models.Venues))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("EnduranceGoals.Model", "FK_GoalParticipants_GoalId", "Goals", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EnduranceGoals.Models.Goals), "GoalParticipants", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnduranceGoals.Models.GoalParticipants))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("EnduranceGoals.Model", "FK_GoalParticipants_UserId", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EnduranceGoals.Models.Users), "GoalParticipants", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnduranceGoals.Models.GoalParticipants))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("EnduranceGoals.Model", "FK_Goals_SportId", "Sports", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EnduranceGoals.Models.Sports), "Goals", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnduranceGoals.Models.Goals))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("EnduranceGoals.Model", "FK_Goals_UserCreatorId", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EnduranceGoals.Models.Users), "Goals", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnduranceGoals.Models.Goals))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("EnduranceGoals.Model", "FK_Goals_VenueId", "Venues", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EnduranceGoals.Models.Venues), "Goals", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnduranceGoals.Models.Goals))]

// Original file name:
// Generation date: 25/10/2012 08:57:23
namespace EnduranceGoals.Models
{
    
    /// <summary>
    /// There are no comments for EnduranceGoalsEntities in the schema.
    /// </summary>
    public partial class EnduranceGoalsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new EnduranceGoalsEntities object using the connection string found in the 'EnduranceGoalsEntities' section of the application configuration file.
        /// </summary>
        public EnduranceGoalsEntities() : 
                base("name=EnduranceGoalsEntities", "EnduranceGoalsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new EnduranceGoalsEntities object.
        /// </summary>
        public EnduranceGoalsEntities(string connectionString) : 
                base(connectionString, "EnduranceGoalsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new EnduranceGoalsEntities object.
        /// </summary>
        public EnduranceGoalsEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "EnduranceGoalsEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Cities> Cities
        {
            get
            {
                if ((this._Cities == null))
                {
                    this._Cities = base.CreateQuery<Cities>("[Cities]");
                }
                return this._Cities;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Cities> _Cities;
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Countries> Countries
        {
            get
            {
                if ((this._Countries == null))
                {
                    this._Countries = base.CreateQuery<Countries>("[Countries]");
                }
                return this._Countries;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Countries> _Countries;
        /// <summary>
        /// There are no comments for GoalParticipants in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<GoalParticipants> GoalParticipants
        {
            get
            {
                if ((this._GoalParticipants == null))
                {
                    this._GoalParticipants = base.CreateQuery<GoalParticipants>("[GoalParticipants]");
                }
                return this._GoalParticipants;
            }
        }
        private global::System.Data.Objects.ObjectQuery<GoalParticipants> _GoalParticipants;
        /// <summary>
        /// There are no comments for Goals in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Goals> Goals
        {
            get
            {
                if ((this._Goals == null))
                {
                    this._Goals = base.CreateQuery<Goals>("[Goals]");
                }
                return this._Goals;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Goals> _Goals;
        /// <summary>
        /// There are no comments for Sports in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Sports> Sports
        {
            get
            {
                if ((this._Sports == null))
                {
                    this._Sports = base.CreateQuery<Sports>("[Sports]");
                }
                return this._Sports;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Sports> _Sports;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Users> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<Users>("[Users]");
                }
                return this._Users;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Users> _Users;
        /// <summary>
        /// There are no comments for Venues in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Venues> Venues
        {
            get
            {
                if ((this._Venues == null))
                {
                    this._Venues = base.CreateQuery<Venues>("[Venues]");
                }
                return this._Venues;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Venues> _Venues;
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        public void AddToCities(Cities cities)
        {
            base.AddObject("Cities", cities);
        }
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        public void AddToCountries(Countries countries)
        {
            base.AddObject("Countries", countries);
        }
        /// <summary>
        /// There are no comments for GoalParticipants in the schema.
        /// </summary>
        public void AddToGoalParticipants(GoalParticipants goalParticipants)
        {
            base.AddObject("GoalParticipants", goalParticipants);
        }
        /// <summary>
        /// There are no comments for Goals in the schema.
        /// </summary>
        public void AddToGoals(Goals goals)
        {
            base.AddObject("Goals", goals);
        }
        /// <summary>
        /// There are no comments for Sports in the schema.
        /// </summary>
        public void AddToSports(Sports sports)
        {
            base.AddObject("Sports", sports);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
        /// <summary>
        /// There are no comments for Venues in the schema.
        /// </summary>
        public void AddToVenues(Venues venues)
        {
            base.AddObject("Venues", venues);
        }
    }
    /// <summary>
    /// There are no comments for EnduranceGoals.Model.Cities in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EnduranceGoals.Model", Name="Cities")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cities : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Cities object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="id">Initial value of Id.</param>
        public static Cities CreateCities(string name, int id)
        {
            Cities cities = new Cities();
            cities.Name = name;
            cities.Id = id;
            return cities;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_Cities_CountryId", "Countries")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Countries Countries
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Countries>("EnduranceGoals.Model.FK_Cities_CountryId", "Countries").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Countries>("EnduranceGoals.Model.FK_Cities_CountryId", "Countries").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Countries> CountriesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Countries>("EnduranceGoals.Model.FK_Cities_CountryId", "Countries");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Countries>("EnduranceGoals.Model.FK_Cities_CountryId", "Countries", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Venues in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_Venues_CityId", "Venues")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Venues> Venues
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Venues>("EnduranceGoals.Model.FK_Venues_CityId", "Venues");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Venues>("EnduranceGoals.Model.FK_Venues_CityId", "Venues", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for EnduranceGoals.Model.Countries in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EnduranceGoals.Model", Name="Countries")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Countries : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Countries object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="id">Initial value of Id.</param>
        public static Countries CreateCountries(string name, int id)
        {
            Countries countries = new Countries();
            countries.Name = name;
            countries.Id = id;
            return countries;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_Cities_CountryId", "Cities")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Cities> Cities
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Cities>("EnduranceGoals.Model.FK_Cities_CountryId", "Cities");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Cities>("EnduranceGoals.Model.FK_Cities_CountryId", "Cities", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for EnduranceGoals.Model.GoalParticipants in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserId
    /// GoalId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EnduranceGoals.Model", Name="GoalParticipants")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class GoalParticipants : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new GoalParticipants object.
        /// </summary>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="goalId">Initial value of GoalId.</param>
        public static GoalParticipants CreateGoalParticipants(int userId, int goalId)
        {
            GoalParticipants goalParticipants = new GoalParticipants();
            goalParticipants.UserId = userId;
            goalParticipants.GoalId = goalId;
            return goalParticipants;
        }
        /// <summary>
        /// There are no comments for Property SignedOnDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> SignedOnDate
        {
            get
            {
                return this._SignedOnDate;
            }
            set
            {
                this.OnSignedOnDateChanging(value);
                this.ReportPropertyChanging("SignedOnDate");
                this._SignedOnDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SignedOnDate");
                this.OnSignedOnDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _SignedOnDate;
        partial void OnSignedOnDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnSignedOnDateChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this.ReportPropertyChanging("UserId");
                this._UserId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
        private int _UserId;
        partial void OnUserIdChanging(int value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property GoalId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int GoalId
        {
            get
            {
                return this._GoalId;
            }
            set
            {
                this.OnGoalIdChanging(value);
                this.ReportPropertyChanging("GoalId");
                this._GoalId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GoalId");
                this.OnGoalIdChanged();
            }
        }
        private int _GoalId;
        partial void OnGoalIdChanging(int value);
        partial void OnGoalIdChanged();
        /// <summary>
        /// There are no comments for Goals in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_GoalParticipants_GoalId", "Goals")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Goals Goals
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Goals>("EnduranceGoals.Model.FK_GoalParticipants_GoalId", "Goals").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Goals>("EnduranceGoals.Model.FK_GoalParticipants_GoalId", "Goals").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Goals in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Goals> GoalsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Goals>("EnduranceGoals.Model.FK_GoalParticipants_GoalId", "Goals");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Goals>("EnduranceGoals.Model.FK_GoalParticipants_GoalId", "Goals", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_GoalParticipants_UserId", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Users Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("EnduranceGoals.Model.FK_GoalParticipants_UserId", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("EnduranceGoals.Model.FK_GoalParticipants_UserId", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Users> UsersReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("EnduranceGoals.Model.FK_GoalParticipants_UserId", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Users>("EnduranceGoals.Model.FK_GoalParticipants_UserId", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for EnduranceGoals.Model.Goals in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EnduranceGoals.Model", Name="Goals")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Goals : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Goals object.
        /// </summary>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="createdOn">Initial value of CreatedOn.</param>
        /// <param name="id">Initial value of Id.</param>
        public static Goals CreateGoals(global::System.DateTime date, string name, global::System.DateTime createdOn, int id)
        {
            Goals goals = new Goals();
            goals.Date = date;
            goals.Name = name;
            goals.CreatedOn = createdOn;
            goals.Id = id;
            return goals;
        }
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this.ReportPropertyChanging("Date");
                this._Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Date");
                this.OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property EventWeb in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EventWeb
        {
            get
            {
                return this._EventWeb;
            }
            set
            {
                this.OnEventWebChanging(value);
                this.ReportPropertyChanging("EventWeb");
                this._EventWeb = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EventWeb");
                this.OnEventWebChanged();
            }
        }
        private string _EventWeb;
        partial void OnEventWebChanging(string value);
        partial void OnEventWebChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this.ReportPropertyChanging("CreatedOn");
                this._CreatedOn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedOn");
                this.OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for GoalParticipants in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_GoalParticipants_GoalId", "GoalParticipants")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<GoalParticipants> GoalParticipants
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<GoalParticipants>("EnduranceGoals.Model.FK_GoalParticipants_GoalId", "GoalParticipants");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<GoalParticipants>("EnduranceGoals.Model.FK_GoalParticipants_GoalId", "GoalParticipants", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Sports in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_Goals_SportId", "Sports")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Sports Sports
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Sports>("EnduranceGoals.Model.FK_Goals_SportId", "Sports").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Sports>("EnduranceGoals.Model.FK_Goals_SportId", "Sports").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Sports in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Sports> SportsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Sports>("EnduranceGoals.Model.FK_Goals_SportId", "Sports");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Sports>("EnduranceGoals.Model.FK_Goals_SportId", "Sports", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_Goals_UserCreatorId", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Users Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("EnduranceGoals.Model.FK_Goals_UserCreatorId", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("EnduranceGoals.Model.FK_Goals_UserCreatorId", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Users> UsersReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("EnduranceGoals.Model.FK_Goals_UserCreatorId", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Users>("EnduranceGoals.Model.FK_Goals_UserCreatorId", "Users", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Venues in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_Goals_VenueId", "Venues")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Venues Venues
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Venues>("EnduranceGoals.Model.FK_Goals_VenueId", "Venues").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Venues>("EnduranceGoals.Model.FK_Goals_VenueId", "Venues").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Venues in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Venues> VenuesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Venues>("EnduranceGoals.Model.FK_Goals_VenueId", "Venues");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Venues>("EnduranceGoals.Model.FK_Goals_VenueId", "Venues", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for EnduranceGoals.Model.Sports in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EnduranceGoals.Model", Name="Sports")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Sports : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Sports object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="id">Initial value of Id.</param>
        public static Sports CreateSports(string name, int id)
        {
            Sports sports = new Sports();
            sports.Name = name;
            sports.Id = id;
            return sports;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Goals in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_Goals_SportId", "Goals")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Goals> Goals
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Goals>("EnduranceGoals.Model.FK_Goals_SportId", "Goals");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Goals>("EnduranceGoals.Model.FK_Goals_SportId", "Goals", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for EnduranceGoals.Model.Users in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EnduranceGoals.Model", Name="Users")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Users : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="createdOn">Initial value of CreatedOn.</param>
        /// <param name="lastname">Initial value of Lastname.</param>
        /// <param name="email">Initial value of Email.</param>
        /// <param name="username">Initial value of Username.</param>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="id">Initial value of Id.</param>
        public static Users CreateUsers(string name, global::System.DateTime createdOn, string lastname, string email, string username, string password, int id)
        {
            Users users = new Users();
            users.Name = name;
            users.CreatedOn = createdOn;
            users.Lastname = lastname;
            users.Email = email;
            users.Username = username;
            users.Password = password;
            users.Id = id;
            return users;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CreatedOn in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return this._CreatedOn;
            }
            set
            {
                this.OnCreatedOnChanging(value);
                this.ReportPropertyChanging("CreatedOn");
                this._CreatedOn = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedOn");
                this.OnCreatedOnChanged();
            }
        }
        private global::System.DateTime _CreatedOn;
        partial void OnCreatedOnChanging(global::System.DateTime value);
        partial void OnCreatedOnChanged();
        /// <summary>
        /// There are no comments for Property Lastname in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname
        {
            get
            {
                return this._Lastname;
            }
            set
            {
                this.OnLastnameChanging(value);
                this.ReportPropertyChanging("Lastname");
                this._Lastname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Lastname");
                this.OnLastnameChanged();
            }
        }
        private string _Lastname;
        partial void OnLastnameChanging(string value);
        partial void OnLastnameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Username in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                this.OnUsernameChanging(value);
                this.ReportPropertyChanging("Username");
                this._Username = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Username");
                this.OnUsernameChanged();
            }
        }
        private string _Username;
        partial void OnUsernameChanging(string value);
        partial void OnUsernameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for GoalParticipants in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_GoalParticipants_UserId", "GoalParticipants")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<GoalParticipants> GoalParticipants
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<GoalParticipants>("EnduranceGoals.Model.FK_GoalParticipants_UserId", "GoalParticipants");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<GoalParticipants>("EnduranceGoals.Model.FK_GoalParticipants_UserId", "GoalParticipants", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Goals in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_Goals_UserCreatorId", "Goals")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Goals> Goals
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Goals>("EnduranceGoals.Model.FK_Goals_UserCreatorId", "Goals");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Goals>("EnduranceGoals.Model.FK_Goals_UserCreatorId", "Goals", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for EnduranceGoals.Model.Venues in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EnduranceGoals.Model", Name="Venues")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Venues : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Venues object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="id">Initial value of Id.</param>
        public static Venues CreateVenues(string name, int id)
        {
            Venues venues = new Venues();
            venues.Name = name;
            venues.Id = id;
            return venues;
        }
        /// <summary>
        /// There are no comments for Property Latitude in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this.OnLatitudeChanging(value);
                this.ReportPropertyChanging("Latitude");
                this._Latitude = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Latitude");
                this.OnLatitudeChanged();
            }
        }
        private global::System.Nullable<double> _Latitude;
        partial void OnLatitudeChanging(global::System.Nullable<double> value);
        partial void OnLatitudeChanged();
        /// <summary>
        /// There are no comments for Property Longitude in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this.OnLongitudeChanging(value);
                this.ReportPropertyChanging("Longitude");
                this._Longitude = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Longitude");
                this.OnLongitudeChanged();
            }
        }
        private global::System.Nullable<double> _Longitude;
        partial void OnLongitudeChanging(global::System.Nullable<double> value);
        partial void OnLongitudeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_Venues_CityId", "Cities")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Cities Cities
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cities>("EnduranceGoals.Model.FK_Venues_CityId", "Cities").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cities>("EnduranceGoals.Model.FK_Venues_CityId", "Cities").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Cities in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Cities> CitiesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Cities>("EnduranceGoals.Model.FK_Venues_CityId", "Cities");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Cities>("EnduranceGoals.Model.FK_Venues_CityId", "Cities", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Goals in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EnduranceGoals.Model", "FK_Goals_VenueId", "Goals")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Goals> Goals
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Goals>("EnduranceGoals.Model.FK_Goals_VenueId", "Goals");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Goals>("EnduranceGoals.Model.FK_Goals_VenueId", "Goals", value);
                }
            }
        }
    }
}
